// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyagc2FEsnwuZUrUk3dxWk5n4Jpg02wSw',
    appId: '1:60410253676:web:2261cf48edcbb654d26349',
    messagingSenderId: '60410253676',
    projectId: 'login-7c128',
    authDomain: 'login-7c128.firebaseapp.com',
    storageBucket: 'login-7c128.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2nXtOQpvhiyQI_HffkW9AFsyOLWBJtTg',
    appId: '1:60410253676:android:51cb3f66955ab72fd26349',
    messagingSenderId: '60410253676',
    projectId: 'login-7c128',
    storageBucket: 'login-7c128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyFaM82EvsXFItWFKcx1gLcmmxKu-QEF8',
    appId: '1:60410253676:ios:4d39f7547dc32f91d26349',
    messagingSenderId: '60410253676',
    projectId: 'login-7c128',
    storageBucket: 'login-7c128.appspot.com',
    iosBundleId: 'com.wjbp.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyFaM82EvsXFItWFKcx1gLcmmxKu-QEF8',
    appId: '1:60410253676:ios:a37b34d1553d51e6d26349',
    messagingSenderId: '60410253676',
    projectId: 'login-7c128',
    storageBucket: 'login-7c128.appspot.com',
    iosBundleId: 'com.wjbp.login.RunnerTests',
  );
}
